# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtt_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rtt_service.proto\x12\x03rtt\"\x1a\n\nRTTRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"%\n\x0bRTTResponse\x12\x16\n\x0ereceived_bytes\x18\x01 \x01(\x03\x32?\n\nRTTService\x12\x31\n\nMeasureRTT\x12\x0f.rtt.RTTRequest\x1a\x10.rtt.RTTResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rtt_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RTTREQUEST']._serialized_start=26
  _globals['_RTTREQUEST']._serialized_end=52
  _globals['_RTTRESPONSE']._serialized_start=54
  _globals['_RTTRESPONSE']._serialized_end=91
  _globals['_RTTSERVICE']._serialized_start=93
  _globals['_RTTSERVICE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
