# Tutorial: https://www.youtube.com/watch?v=zj6r_EEhv6s
deploy:
	 kubectl apply -f deployment/kube/workflow_worker/worker-deployment1.yaml
	 kubectl apply -f deployment/kube/workflow_worker/worker-deployment2.yaml
	 kubectl apply -f deployment/kube/workflow_worker/worker-service.yaml
delete:
	kubectl delete -f deployment/kube/workflow_worker/worker-deployment1.yaml
	kubectl delete -f deployment/kube/workflow_worker/worker-deployment2.yaml
	kubectl delete -f deployment/kube/workflow_worker/worker-service.yaml