# Tutorial: https://www.youtube.com/watch?v=zj6r_EEhv6s
deploy:
	 kubectl apply -f worker-deployment1.yaml
	 kubectl apply -f worker-deployment2.yaml
#	 kubectl apply -f worker-deployment3.yaml
#	 kubectl apply -f worker-deployment4.yaml
	 kubectl apply -f worker-service1.yaml
	 kubectl apply -f worker-service2.yaml
#	 kubectl apply -f worker-service3.yaml
#	 kubectl apply -f worker-service4.yaml

delete:
	kubectl delete -f worker-deployment1.yaml
#	kubectl delete -f worker-deployment2.yaml
#	kubectl delete -f worker-deployment3.yaml
#	kubectl delete -f worker-deployment4.yaml
	kubectl delete -f worker-service1.yaml
#	kubectl delete -f worker-service2.yaml
#	kubectl delete -f worker-service3.yaml
#	kubectl delete -f worker-service4.yaml