apiVersion: v1
kind: Service
metadata:
  name: workflow-worker-service-1
  labels:
    app: workflow-worker-1
spec:
  ports:
    - protocol: "TCP"
      port: 5003
      targetPort: 5003
  selector:
    app: workflow-worker-1