apiVersion: v1
kind: Service
metadata:
  name: minion-service
  labels:
    app: minion
spec:
  clusterIP: None
  ports:
    - protocol: "TCP"
      port: 50000
      targetPort: 50000
      name: minion
  selector:
    app: minion
