apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: DaemonSet
metadata:
  name: minion
spec:
  selector:
    matchLabels:
      app: minion
  template:
    metadata:
      labels:
        app: minion
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf-1
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 998
        runAsGroup: 22
      hostIPC: True
      containers:
        - name: minion
          image: adarshzededa/cdi-minion:latest
          imagePullPolicy: Always
          env:
            - name: RPC_HOST
              value: "0.0.0.0"
            - name: RPC_PORT
              value: "50000"
            - name: RDMA_HOST
              value: "0.0.0.0"
            - name: RDMA_PORT
              value: "12345"
            - name: SQL_HOST
              value: "postgres"
            - name: SQL_PORT
              value: "5432"
            - name: SQL_USER
              value: "admin"
            - name: SQL_PASSWORD
              value: "admin"
            - name: SQL_DB
              value: "cdi"
            - name: CONTROLLER_HOST
              value: "controller-service"
            - name: CONTROLLER_PORT
              value: "50000"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CONTAINER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONTAINER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONTAINER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            capabilities:
              add: [ "IPC_LOCK" ]
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              rdma/hca_shared_devices_a: 1
          ports:
            - containerPort: 50000
              hostPort: 50000
          readinessProbe:
            grpc:
              port: 50000
            periodSeconds: 1
            initialDelaySeconds: 10
          livenessProbe:
            grpc:
              port: 50000
            initialDelaySeconds: 10
            periodSeconds: 60
