apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mofed-test-pod-1
spec:
  selector:
    matchLabels:
      app: minion
  template:
    metadata:
      labels:
        app: minion
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
    spec:
      restartPolicy: Always
      containers:
      - image: mellanox/rping-test
        name: mofed-test-ctr
        securityContext:
          capabilities:
            add: [ "IPC_LOCK" ]
        resources:
          limits:
            rdma/hca_shared_devices_a: 1
        command:
        - sh
        - -c
        - |
          ls -l /dev/infiniband /sys/class/infiniband /sys/class/net
          sleep 1000000