# Tutorial: https://www.youtube.com/watch?v=zj6r_EEhv6s
deploy:
	kubectl apply -f deployment/kube/workflow_controller/deployment.yaml 
	kubectl apply -f  deployment/kube/workflow_controller/service.yaml

delete:
	kubectl delete -f deployment/kube/workflow_controller/deployment.yaml
	kubectl delete -f deployment/kube/workflow_controller/service.yaml
