# Tutorial: https://www.youtube.com/watch?v=zj6r_EEhv6s
deploy:
	kubectl apply -f configmap.yaml
	kubectl apply -f daemonset.yaml

delete:
	kubectl delete -f daemonset.yaml
	kubectl delete -f configmap.yaml