apiVersion: v1
kind: Pod
metadata:
  name: test-rdma-client
  annotations:
    k8s.v1.cni.cncf.io/networks: whereabouts-conf
  labels:
    app: test-rdma-client
    role: test-rdma-client
spec:
  restartPolicy: OnFailure
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: role
                operator: In
                values:
                  - test-rdma-server
          topologyKey: "kubernetes.io/hostname"
  containers:
    - name: test-rdma-client
      image: 135642/cdi-rdma
      securityContext:
        capabilities:
          add: [ "IPC_LOCK" ]
      resources:
        limits:
          rdma/hca_shared_devices_a: "1"
      command:
        - sh
        - -c
        - |
          ls -l /dev/infiniband /sys/class/infiniband /sys/class/net
          sleep infinity