apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod
spec:
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
      annotations:
        k8s.v1.cni.cncf.io/networks: whereabouts-conf
    spec:
#      restartPolicy: Always
      hostIPC: True
      containers:
        - name: pod
          image: 135642/rdma
          securityContext:
            capabilities:
              add: [ "IPC_LOCK" ]
#            runAsUser: 998
#            runAsGroup: 22
#          env:
#            - name: RPC_HOST
#              value: "0.0.0.0"
#            - name: RPC_PORT
#              value: "50000"
#            - name: RDMA_PORT
#              value: "12345"
#            - name: SQL_HOST
#              value: "postgres"
#            - name: SQL_PORT
#              value: "5432"
#            - name: SQL_USER
#              value: "admin"
#            - name: SQL_PASSWORD
#              value: "admin"
#            - name: SQL_DB
#              value: "cdi"
#            - name: CONTROLLER_HOST
#              value: "controller-service"
#            - name: CONTROLLER_PORT
#              value: "50000"
#            - name: NODE_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.hostIP
#            - name: CONTAINER_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#            - name: CONTAINER_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.podIP
#            - name: CONTAINER_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "200Mi"
            limits:
              rdma/hca_shared_devices_a: 1
              memory: "1Gi"
#          ports:
#            - containerPort: 50001
#              hostPort: 50001
          command:
            - "/bin/sh"
            - "-c"
            - "sleep 60m"