version: '3'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass supersecurepassword
    volumes:
      - redis-data:/data
    networks:
      cdi-network: { }

  extractor:
    image: shirinebadi/cdi-extractor:latest
    platform: "linux/arm64"
    restart: always
    ports:
      - "50000:50000"
    environment:
      HOST: "0.0.0.0"
      PORT: 50000
      NEXT_RPC_HOST: detector
      NEXT_RPC_PORT: 50000
      LOCAL_BUFFER_DIR: "/tmp"
      SERVER_TYPE_ENV: "tcp"
      SQL_HOST_ENV: "db"
    networks:
      cdi-network: { }

  detector:
    image: shirinebadi/cdi-detector:latest
    platform: "linux/arm64"
    restart: always
    environment:
      RPC_HOST: "0.0.0.0"
      RPC_PORT: 50000
      NEXT_RPC_HOST: combiner
      NEXT_RPC_PORT: 50000
      SERVER_TYPE_ENV: "tcp"
    networks:
      cdi-network: { }

  combiner:
    image: shirinebadi/cdi-combiner:latest
    platform: "linux/arm64"
    restart: always
    environment:
      RPC_HOST: "0.0.0.0"
      RPC_PORT: 50000
      CACHE_DB_HOST: cache
      CACHE_DB_PORT: 6379
      CACHE_DB_PWD: "supersecurepassword"
      LOCAL_BUFFER_DIR: "/tmp"
      SERVER_TYPE_ENV: "tcp"
    networks:
      cdi-network: { }

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: "eval"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      cdi-network: { }


volumes:
  redis-data:
    driver: local

networks:
  cdi-network:
    driver: bridge