version: '3'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass supersecurepassword
    volumes:
      - redis-data:/data
    networks:
      cdi-network: { }

  extractor:
    image: adarshzededa/cdi-extractor-rpc:latest
#    platform: "linux/amd64"
    restart: always
    ports:
      - "50000:50000"
    build:
      context: ../../
      dockerfile: srvs/extractor/Dockerfile
      args:
        - service=extractor
    environment:
      HOST: "0.0.0.0"
      PORT: 50000
      NEXT_RPC_HOST: object_detector
      NEXT_RPC_PORT: 50000
      LOCAL_BUFFER_DIR: "/tmp"
    networks:
      cdi-network: { }

  object_detector:
    image: adarshzededa/cdi-objdetector-rpc:latest
#    platform: "linux/amd64"
    restart: always
    build:
      context: ../../
      dockerfile: srvs/object_detector/Dockerfile
      args:
        - service=object_detector
    environment:
      RPC_HOST: "0.0.0.0"
      RPC_PORT: 50000
      NEXT_RPC_HOST: combiner
      NEXT_RPC_PORT: 50000
    networks:
      cdi-network: { }

  combiner:
    image: adarshzededa/cdi-combiner-rpc:latest
#    platform: "linux/amd64"
    restart: always
    build:
      context: ../../
      dockerfile: srvs/combiner/Dockerfile
      args:
        - service=combiner
    environment:
      RPC_HOST: "0.0.0.0"
      RPC_PORT: 50000
      CACHE_DB_HOST: cache
      CACHE_DB_PORT: 6379
      CACHE_DB_PWD: "supersecurepassword"
      LOCAL_BUFFER_DIR: "/tmp"
    networks:
      cdi-network: { }

volumes:
  redis-data:
    driver: local

networks:
  cdi-network:
    driver: bridge