# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minion-api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import controller_api_pb2 as controller__api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10minion-api.proto\x12\x05proto\x1a\x14\x63ontroller-api.proto\"@\n\x17MinionCreateCDIsRequest\x12%\n\x0b\x63\x64i_configs\x18\x01 \x03(\x0b\x32\x10.proto.CdiConfig\"\'\n\x18MinionCreateCDIsResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\t\"@\n\x17MinionUpdateCDIsRequest\x12%\n\x0b\x63\x64i_configs\x18\x01 \x03(\x0b\x32\x10.proto.CdiConfig\"\'\n\x18MinionUpdateCDIsResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\t\"y\n\"MinionTransferAndDeleteCDIsRequest\x12\x15\n\rtransfer_host\x18\x01 \x01(\t\x12\x15\n\rtransfer_port\x18\x02 \x01(\t\x12%\n\x0b\x63\x64i_configs\x18\x03 \x03(\x0b\x32\x10.proto.CdiConfig\"2\n#MinionTransferAndDeleteCDIsResponse\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\"@\n\x17MinionDeleteCDIsRequest\x12%\n\x0b\x63\x64i_configs\x18\x01 \x03(\x0b\x32\x10.proto.CdiConfig\"\'\n\x18MinionDeleteCDIsResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\t2\xfe\x02\n\x17MinionControllerService\x12O\n\nCreateCDIs\x12\x1e.proto.MinionCreateCDIsRequest\x1a\x1f.proto.MinionCreateCDIsResponse\"\x00\x12O\n\nUpdateCDIs\x12\x1e.proto.MinionUpdateCDIsRequest\x1a\x1f.proto.MinionUpdateCDIsResponse\"\x00\x12p\n\x15TransferAndDeleteCDIs\x12).proto.MinionTransferAndDeleteCDIsRequest\x1a*.proto.MinionTransferAndDeleteCDIsResponse\"\x00\x12O\n\nDeleteCDIs\x12\x1e.proto.MinionDeleteCDIsRequest\x1a\x1f.proto.MinionDeleteCDIsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minion_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MINIONCREATECDISREQUEST']._serialized_start=49
  _globals['_MINIONCREATECDISREQUEST']._serialized_end=113
  _globals['_MINIONCREATECDISRESPONSE']._serialized_start=115
  _globals['_MINIONCREATECDISRESPONSE']._serialized_end=154
  _globals['_MINIONUPDATECDISREQUEST']._serialized_start=156
  _globals['_MINIONUPDATECDISREQUEST']._serialized_end=220
  _globals['_MINIONUPDATECDISRESPONSE']._serialized_start=222
  _globals['_MINIONUPDATECDISRESPONSE']._serialized_end=261
  _globals['_MINIONTRANSFERANDDELETECDISREQUEST']._serialized_start=263
  _globals['_MINIONTRANSFERANDDELETECDISREQUEST']._serialized_end=384
  _globals['_MINIONTRANSFERANDDELETECDISRESPONSE']._serialized_start=386
  _globals['_MINIONTRANSFERANDDELETECDISRESPONSE']._serialized_end=436
  _globals['_MINIONDELETECDISREQUEST']._serialized_start=438
  _globals['_MINIONDELETECDISREQUEST']._serialized_end=502
  _globals['_MINIONDELETECDISRESPONSE']._serialized_start=504
  _globals['_MINIONDELETECDISRESPONSE']._serialized_end=543
  _globals['_MINIONCONTROLLERSERVICE']._serialized_start=546
  _globals['_MINIONCONTROLLERSERVICE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
