# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minion-api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10minion-api.proto\x12\x05proto\"\xbf\x01\n\x0fMinionCdiConfig\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x02 \x01(\t\x12\x0e\n\x06\x63\x64i_id\x18\x03 \x01(\t\x12\x0f\n\x07shm_key\x18\x04 \x01(\x05\x12\x11\n\tshm_shmid\x18\x05 \x01(\x05\x12\x11\n\tshm_segsz\x18\x06 \x01(\x05\x12\x10\n\x08shm_mode\x18\x07 \x01(\x05\x12\x0f\n\x07shm_uid\x18\x08 \x01(\x05\x12\x0f\n\x07shm_gid\x18\t \x01(\x05\x12\x0f\n\x07payload\x18\n \x01(\t\"F\n\x17MinionCreateCDIsRequest\x12+\n\x0b\x63\x64i_configs\x18\x01 \x03(\x0b\x32\x16.proto.MinionCdiConfig\"T\n\x18MinionCreateCDIsResponse\x12+\n\x0b\x63\x64i_configs\x18\x01 \x03(\x0b\x32\x16.proto.MinionCdiConfig\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\"F\n\x17MinionUpdateCDIsRequest\x12+\n\x0b\x63\x64i_configs\x18\x01 \x03(\x0b\x32\x16.proto.MinionCdiConfig\"T\n\x18MinionUpdateCDIsResponse\x12+\n\x0b\x63\x64i_configs\x18\x01 \x03(\x0b\x32\x16.proto.MinionCdiConfig\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\"\x7f\n\"MinionTransferAndDeleteCDIsRequest\x12\x15\n\rtransfer_host\x18\x01 \x01(\t\x12\x15\n\rtransfer_port\x18\x02 \x01(\t\x12+\n\x0b\x63\x64i_configs\x18\x03 \x03(\x0b\x32\x16.proto.MinionCdiConfig\"2\n#MinionTransferAndDeleteCDIsResponse\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\"F\n\x17MinionDeleteCDIsRequest\x12+\n\x0b\x63\x64i_configs\x18\x01 \x03(\x0b\x32\x16.proto.MinionCdiConfig\"\'\n\x18MinionDeleteCDIsResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\t2\xfe\x02\n\x17MinionControllerService\x12O\n\nCreateCDIs\x12\x1e.proto.MinionCreateCDIsRequest\x1a\x1f.proto.MinionCreateCDIsResponse\"\x00\x12O\n\nUpdateCDIs\x12\x1e.proto.MinionUpdateCDIsRequest\x1a\x1f.proto.MinionUpdateCDIsResponse\"\x00\x12p\n\x15TransferAndDeleteCDIs\x12).proto.MinionTransferAndDeleteCDIsRequest\x1a*.proto.MinionTransferAndDeleteCDIsResponse\"\x00\x12O\n\nDeleteCDIs\x12\x1e.proto.MinionDeleteCDIsRequest\x1a\x1f.proto.MinionDeleteCDIsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minion_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MINIONCDICONFIG']._serialized_start=28
  _globals['_MINIONCDICONFIG']._serialized_end=219
  _globals['_MINIONCREATECDISREQUEST']._serialized_start=221
  _globals['_MINIONCREATECDISREQUEST']._serialized_end=291
  _globals['_MINIONCREATECDISRESPONSE']._serialized_start=293
  _globals['_MINIONCREATECDISRESPONSE']._serialized_end=377
  _globals['_MINIONUPDATECDISREQUEST']._serialized_start=379
  _globals['_MINIONUPDATECDISREQUEST']._serialized_end=449
  _globals['_MINIONUPDATECDISRESPONSE']._serialized_start=451
  _globals['_MINIONUPDATECDISRESPONSE']._serialized_end=535
  _globals['_MINIONTRANSFERANDDELETECDISREQUEST']._serialized_start=537
  _globals['_MINIONTRANSFERANDDELETECDISREQUEST']._serialized_end=664
  _globals['_MINIONTRANSFERANDDELETECDISRESPONSE']._serialized_start=666
  _globals['_MINIONTRANSFERANDDELETECDISRESPONSE']._serialized_end=716
  _globals['_MINIONDELETECDISREQUEST']._serialized_start=718
  _globals['_MINIONDELETECDISREQUEST']._serialized_end=788
  _globals['_MINIONDELETECDISRESPONSE']._serialized_start=790
  _globals['_MINIONDELETECDISRESPONSE']._serialized_end=829
  _globals['_MINIONCONTROLLERSERVICE']._serialized_start=832
  _globals['_MINIONCONTROLLERSERVICE']._serialized_end=1214
# @@protoc_insertion_point(module_scope)
