# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: process-api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import controller_api_pb2 as controller__api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11process-api.proto\x12\x05proto\x1a\x14\x63ontroller-api.proto\"J\n\x17NotifyCDIsAccessRequest\x12/\n\x0b\x63\x64i_configs\x18\x01 \x03(\x0b\x32\x1a.proto.ControllerCdiConfig\"\'\n\x18NotifyCDIsAccessResponse\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t2g\n\x0eProcessService\x12U\n\x10NotifyCDIsAccess\x12\x1e.proto.NotifyCDIsAccessRequest\x1a\x1f.proto.NotifyCDIsAccessResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'process_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYCDISACCESSREQUEST']._serialized_start=50
  _globals['_NOTIFYCDISACCESSREQUEST']._serialized_end=124
  _globals['_NOTIFYCDISACCESSRESPONSE']._serialized_start=126
  _globals['_NOTIFYCDISACCESSRESPONSE']._serialized_end=165
  _globals['_PROCESSSERVICE']._serialized_start=167
  _globals['_PROCESSSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
