apiVersion: v1
kind: Service
metadata:
  name: detector-service
  labels:
    app: detector
spec:
  clusterIP: None
  ports:
    - protocol: "TCP"
      port: 50000
      targetPort: 50000
      name: detector
  selector:
    app: detector
