# Tutorial: https://www.youtube.com/watch?v=zj6r_EEhv6s
deploy:
    kubectl apply -f deployment/kube/workflow_scheduler/scheduler-deployment.yaml 
	kubectl apply -f  deployment/kube/workflow_scheduler/scheduler-service.yaml

delete:
	kubectl delete -f deployment/kube/workflow_scheduler/scheduler-deployment.yaml
	kubectl delete -f deployment/kube/workflow_scheduler/scheduler-service.yaml
