# Tutorial: https://www.youtube.com/watch?v=zj6r_EEhv6s
deploy:
	kubectl apply -f scheduler-deployment.yaml
	kubectl apply -f  scheduler-service.yaml

delete:
	kubectl delete -f scheduler-deployment.yaml
	kubectl delete -f scheduler-service.yaml
