apiVersion: v1
kind: Service
metadata:
  name: controller-service
  labels:
    app: controller
spec:
  clusterIP: None
  ports:
    - protocol: "TCP"
      port: 50000
      targetPort: 50000
      name: controller
  selector:
    app: controller
