apiVersion: v1
kind: Service
metadata:
  name: extractor-service
  labels:
    app: extractor
spec:
  clusterIP: None
  ports:
    - protocol: "TCP"
      port: 50000
      targetPort: 50000
      name: extractor
  selector:
    app: extractor
